import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/src/shared/common/Navbar";
import Providers from "@/src/app/providers";
import { AuthBootstrapper } from "@/src/app/AuthBootstrapper";
import TenantBootstrapper from "@/src/app/TenantBootstrapper";
import { BootstrapGate } from "@/src/app/BootstrapGate";
import { QueryParamProvider } from "@/src/utils/queryParamProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-bg`}
      >
        <Providers>
          <BootstrapGate
            bootstrappers={
              <>
                <AuthBootstrapper />
                <TenantBootstrapper />
              </>
            }
          >
            <div className="flex flex-col min-h-full">
              <Navbar />
              <QueryParamProvider>
                {children}
              </QueryParamProvider>
            </div>
          </BootstrapGate>
        </Providers>
      </body>
    </html>
  );
}
